get attractions data from mysql
Natalia0604/taipei-day-trip-website pull request #2
Opened 2021-04-25 06:07 UTC by Natalia0604

1.新增一個程式inputdata.py將json檔的資料匯入mysql並建立兩個資料表(attractions & attractionImage)。
2.在app.py中新增兩個API，將mysql中兩個資料表(attractions & attractionImage)資料顯示在網頁上。

2021-04-25 06:27 UTC, cwpeng requested changes
請把已經上線的網址寫在訊息中，我才能測試確認哦 ~

2021-04-25 06:35 UTC, Natalia0604 commented
我好像搞錯順序了 OMG
我還沒上線網站QQ 抱歉~~

2021-04-25 06:42 UTC, cwpeng commented
全部都寫完再上線倒是沒有搞錯順序，但是要上線到 AWS EC2 上哦 ~

2021-04-29 09:56 UTC, Natalia0604 commented
http://18.178.158.154:3000/api/attraction/10
http://18.178.158.154:3000/api/attractions?page=1
http://18.178.158.154:3000/api/attractions?page=1&keyword=中正紀念堂
老師不好意思~拖了這麼久才交作業，再麻煩您幫我看看有沒有要改進的地方，謝謝: )

2021-04-29 11:13 UTC, cwpeng requested changes
辛苦了，還差一些，我們的關鍵字搜尋是只要景點標題包含搜尋的關鍵字，就應該被顯示出來哦，使用 WHERE LIKE 這個 SQL 語句很快地就能處理。例如以下這個搜尋應該就要有些結果：
http://18.178.158.154:3000/api/attractions?page=0&keyword=步道

2021-04-29 15:38 UTC, Natalia0604 commented
我修改完成了~
想問說這邊的page會變成以keyword搜尋的筆數來做分頁是對的嗎?
如果搜尋結果只有12筆的話就只會page=0有資料，其他都會是空值。
再麻煩老師幫忙看一下我有沒有理解對XD
http://18.178.158.154:3000/api/attractions?page=0&keyword=公園
http://18.178.158.154:3000/api/attractions?page=0&keyword=步道
謝謝~

2021-04-29 15:40 UTC, cwpeng commented
好哦，看起來是 OK 了，不過請重新發一個 Review 邀求給我哦，才有辦法幫你 Approve ~

2021-04-29 15:43 UTC, cwpeng approved these changes
OK. :)

2021-04-29 15:43 UTC, Natalia0604 commented
謝謝老師~
sorry 每次都忘記發XD

2021-04-29 15:44 UTC, merged

2021-04-29 15:45 UTC, cwpeng commented
就請盡量記得嘍 ~ 麻煩惹 XDD